/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.cliente.view;

/**
 *
 * @author hugo.gomes
 */
public class FormCliente extends javax.swing.JFrame  {

    /**
     * Creates new form FormCliente
     */
    public FormCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        contentPane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblPesquisar = new javax.swing.JLabel();
        lblEndereco = new javax.swing.JLabel();
        lblMunicipio = new javax.swing.JLabel();
        lblCEP = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        lblCelular = new javax.swing.JLabel();
        lblCNPJ = new javax.swing.JLabel();
        lblGenero = new javax.swing.JLabel();
        lblCPF = new javax.swing.JLabel();
        lblNomeEmpresa = new javax.swing.JLabel();
        txtMunicipio = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        txtNomeEmpresa = new javax.swing.JTextField();
        cmbPesquisar = new javax.swing.JComboBox<>();
        txtCEP = new javax.swing.JFormattedTextField();
        txtTelefone = new javax.swing.JFormattedTextField();
        txtCelular = new javax.swing.JFormattedTextField();
        bttExcluir = new javax.swing.JButton();
        txtCNPJ = new javax.swing.JFormattedTextField();
        bttPesquisar = new javax.swing.JButton();
        bttEditar = new javax.swing.JButton();
        bttGravar = new javax.swing.JButton();
        bttLimpar = new javax.swing.JButton();
        rbGeneroM = new javax.swing.JRadioButton();
        rbGeneroF = new javax.swing.JRadioButton();
        txtCPF = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(480, 420));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contentPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro de clientes");
        contentPane.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 290, 30));

        lblID.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblID.setText("ID");
        contentPane.add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        lblPesquisar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblPesquisar.setText("Pesquisar");
        contentPane.add(lblPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        lblEndereco.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblEndereco.setText("Endereço");
        contentPane.add(lblEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        lblMunicipio.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblMunicipio.setText("Município");
        contentPane.add(lblMunicipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        lblCEP.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblCEP.setText("CEP");
        contentPane.add(lblCEP, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, 10));

        lblTelefone.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTelefone.setText("Telefone");
        contentPane.add(lblTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        lblCelular.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblCelular.setText("Celular");
        contentPane.add(lblCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        lblCNPJ.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblCNPJ.setText("CNPJ");
        contentPane.add(lblCNPJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        lblGenero.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblGenero.setText("Gênero");
        contentPane.add(lblGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        lblCPF.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblCPF.setText("CPF");
        contentPane.add(lblCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        lblNomeEmpresa.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNomeEmpresa.setText("Nome/Empresa");
        contentPane.add(lblNomeEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));
        contentPane.add(txtMunicipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 250, -1));
        contentPane.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 60, -1));
        contentPane.add(txtEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 250, -1));

        txtNomeEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeEmpresaActionPerformed(evt);
            }
        });
        contentPane.add(txtNomeEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 250, -1));

        contentPane.add(cmbPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 280, -1));
        contentPane.add(txtCEP, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 200, -1));

        txtTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefoneActionPerformed(evt);
            }
        });
        contentPane.add(txtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 200, -1));
        contentPane.add(txtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 200, -1));

        bttExcluir.setIcon(new javax.swing.ImageIcon("D:\\Hugo Christian\\Aplicativos\\Icones\\bttExcluir.png")); // NOI18N
        contentPane.add(bttExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, -1, -1));
        contentPane.add(txtCNPJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 200, -1));

        bttPesquisar.setIcon(new javax.swing.ImageIcon("D:\\Hugo Christian\\Aplicativos\\Icones\\bttPesquisar.png")); // NOI18N
        contentPane.add(bttPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, -1, -1));

        bttEditar.setIcon(new javax.swing.ImageIcon("D:\\Hugo Christian\\Aplicativos\\Icones\\bttEditar.png")); // NOI18N
        contentPane.add(bttEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, -1, -1));

        bttGravar.setIcon(new javax.swing.ImageIcon("D:\\Hugo Christian\\Aplicativos\\Icones\\bttGravar.png")); // NOI18N
        contentPane.add(bttGravar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, -1, -1));

        bttLimpar.setIcon(new javax.swing.ImageIcon("D:\\Hugo Christian\\Aplicativos\\Icones\\bttLimpar.png")); // NOI18N
        contentPane.add(bttLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, -1, -1));

        buttonGroup1.add(rbGeneroM);
        rbGeneroM.setText("M");
        contentPane.add(rbGeneroM, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, -1, -1));

        buttonGroup1.add(rbGeneroF);
        rbGeneroF.setText("F");
        contentPane.add(rbGeneroF, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, -1, -1));
        contentPane.add(txtCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 200, -1));

        getContentPane().add(contentPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeEmpresaActionPerformed

    private void txtTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttEditar;
    private javax.swing.JButton bttExcluir;
    private javax.swing.JButton bttGravar;
    private javax.swing.JButton bttLimpar;
    private javax.swing.JButton bttPesquisar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JComboBox<String> cmbPesquisar;
    private javax.swing.JPanel contentPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCEP;
    private javax.swing.JLabel lblCNPJ;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblMunicipio;
    private javax.swing.JLabel lblNomeEmpresa;
    private javax.swing.JLabel lblPesquisar;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JRadioButton rbGeneroF;
    private javax.swing.JRadioButton rbGeneroM;
    private javax.swing.JFormattedTextField txtCEP;
    private javax.swing.JFormattedTextField txtCNPJ;
    private javax.swing.JFormattedTextField txtCPF;
    private javax.swing.JFormattedTextField txtCelular;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtMunicipio;
    private javax.swing.JTextField txtNomeEmpresa;
    private javax.swing.JFormattedTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
