/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.cliente.view;

import br.com.cliente.bean.Cliente;
import br.com.cliente.controle.ClienteCT;
import br.com.cliente.utils.MaskCampos;
import java.text.ParseException;
import java.util.List;
import javax.swing.JFormattedTextField;

/**
 *
 * @author hugo.gomes
 */
public class FormCliente extends javax.swing.JFrame {

    /**
     * Creates new form FormCliente
     */
    private String genero;

    public FormCliente() {
        initComponents();

        //Chamando o metodo de mascaras
        Mascaras();

        rbGeneroM.setSelected(true);
        
        CarregarLista();
    }

    public void Mascaras() {
        // Inserir os campos de mascaras nos metodos da classe MaskCampos
        MaskCampos mask = new MaskCampos();

        try {

            //mask.maskGeral(txtCEP, "###-####");
            //mask.maskGeral(txtCNPJ, "###-####");
            //mask.maskGeral(txtCPF, "###-####");
            //mask.maskGeral(txtCelular, "###-####");
            //mask.maskGeral(txtTelefone, "###-####");
            new JFormattedTextField(mask.maskCEP(txtCEP));
            new JFormattedTextField(mask.maskCNPJ(txtCNPJ));
            new JFormattedTextField(mask.maskCPF(txtCPF));
            new JFormattedTextField(mask.maskCelular(txtCelular));
            new JFormattedTextField(mask.maskTelefone(txtTelefone));
        } catch (ParseException e) {
            e.printStackTrace();
        }

    }

    public Cliente montaCliente() {
        Cliente c = new Cliente();

        c.setNome(txtNomeEmpresa.getText());
        c.setEndereco(txtEndereco.getText());
        c.setCelular(txtCelular.getText());
        c.setMunicipio(txtMunicipio.getText());
        c.setCep(txtCEP.getText());
        c.setTelefone(txtTelefone.getText());
        c.setCpf(txtCPF.getText());
        c.setCnpj(txtCNPJ.getText());
        c.setGenero(genero);

        if (txtId.getText() != null && !txtId.getText().equals("")) {
            c.setId(Integer.parseInt(txtId.getText()));
        }

        return c;
    }

    public void limparTela() {
        txtId.setText("");
        txtCEP.setText("");
        txtCNPJ.setText("");
        txtCPF.setText("");
        txtCelular.setText("");
        txtEndereco.setText("");
        txtId.setText("");
        txtMunicipio.setText("");
        txtNomeEmpresa.setText("");
        txtTelefone.setText("");
        cmbPesquisar.setSelectedIndex(0);

        rbGeneroM.setSelected(true);

    }

    public void ClienteSelecionado(Cliente c) {
        //Prencher o formulario de cliente selecionado no combobox, ao
        //clicar no botão pesquisar;

        txtNomeEmpresa.setText(c.getNome());
        txtEndereco.setText(c.getEndereco());
        txtCEP.setText(c.getEndereco());
        txtCNPJ.setText(c.getEndereco());
        txtCPF.setText(c.getEndereco());
        txtCelular.setText(c.getEndereco());
        txtMunicipio.setText(c.getEndereco());
        txtTelefone.setText(c.getEndereco());

        if (c.getGenero().equals("F")) {
            rbGeneroF.setSelected(true);
            rbGeneroM.setSelected(false);
        } else if (c.getGenero().equals("M")) {
            rbGeneroM.setSelected(true);
            rbGeneroF.setSelected(false);
        }
        
        if(c.getId() != null && c.getId() >0){
            txtId.setText(c.getId().toString());
        }

    }

    public void CarregarLista(){
        //Instaciando o objeto ClienCT  
        ClienteCT mbc = new ClienteCT();
    
        //Adicionando os valores do banco de dados na minha lista Cliente
        List<Cliente> ClienteDB = mbc.select();
        
        //Remover todos os itens
        cmbPesquisar.removeAllItems();
        
        for (Cliente cliente : ClienteDB) {
            cmbPesquisar.addItem(cliente.getNome());
        }
        
        //for (int i = 0; i < ClienteDB.size(); i++) {
        //    Cliente cliente = ClienteDB.get(i);
        //    cmbPesquisar.addItem(cliente.getNome());
        //}

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        contentPane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblPesquisar = new javax.swing.JLabel();
        lblEndereco = new javax.swing.JLabel();
        lblMunicipio = new javax.swing.JLabel();
        lblCEP = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        lblCelular = new javax.swing.JLabel();
        lblCNPJ = new javax.swing.JLabel();
        lblGenero = new javax.swing.JLabel();
        lblCPF = new javax.swing.JLabel();
        lblNomeEmpresa = new javax.swing.JLabel();
        txtMunicipio = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        txtNomeEmpresa = new javax.swing.JTextField();
        cmbPesquisar = new javax.swing.JComboBox<>();
        txtCEP = new javax.swing.JFormattedTextField();
        txtTelefone = new javax.swing.JFormattedTextField();
        txtCelular = new javax.swing.JFormattedTextField();
        bttExcluir = new javax.swing.JButton();
        txtCNPJ = new javax.swing.JFormattedTextField();
        bttPesquisar = new javax.swing.JButton();
        bttEditar = new javax.swing.JButton();
        bttGravar = new javax.swing.JButton();
        bttLimpar = new javax.swing.JButton();
        rbGeneroM = new javax.swing.JRadioButton();
        rbGeneroF = new javax.swing.JRadioButton();
        txtCPF = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(480, 420));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contentPane.setBackground(new java.awt.Color(0, 51, 51));
        contentPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro de clientes");
        contentPane.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 290, 30));

        lblID.setBackground(new java.awt.Color(255, 255, 255));
        lblID.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblID.setForeground(new java.awt.Color(255, 255, 255));
        lblID.setText("ID");
        contentPane.add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        lblPesquisar.setBackground(new java.awt.Color(255, 255, 255));
        lblPesquisar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        lblPesquisar.setText("Pesquisar");
        contentPane.add(lblPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        lblEndereco.setBackground(new java.awt.Color(255, 255, 255));
        lblEndereco.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblEndereco.setForeground(new java.awt.Color(255, 255, 255));
        lblEndereco.setText("Endereço");
        contentPane.add(lblEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        lblMunicipio.setBackground(new java.awt.Color(255, 255, 255));
        lblMunicipio.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblMunicipio.setForeground(new java.awt.Color(255, 255, 255));
        lblMunicipio.setText("Município");
        contentPane.add(lblMunicipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        lblCEP.setBackground(new java.awt.Color(255, 255, 255));
        lblCEP.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblCEP.setForeground(new java.awt.Color(255, 255, 255));
        lblCEP.setText("CEP");
        contentPane.add(lblCEP, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, 10));

        lblTelefone.setBackground(new java.awt.Color(255, 255, 255));
        lblTelefone.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTelefone.setForeground(new java.awt.Color(255, 255, 255));
        lblTelefone.setText("Telefone");
        contentPane.add(lblTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        lblCelular.setBackground(new java.awt.Color(255, 255, 255));
        lblCelular.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblCelular.setForeground(new java.awt.Color(255, 255, 255));
        lblCelular.setText("Celular");
        contentPane.add(lblCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        lblCNPJ.setBackground(new java.awt.Color(255, 255, 255));
        lblCNPJ.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblCNPJ.setForeground(new java.awt.Color(255, 255, 255));
        lblCNPJ.setText("CNPJ");
        contentPane.add(lblCNPJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        lblGenero.setBackground(new java.awt.Color(255, 255, 255));
        lblGenero.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblGenero.setForeground(new java.awt.Color(255, 255, 255));
        lblGenero.setText("Gênero");
        contentPane.add(lblGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        lblCPF.setBackground(new java.awt.Color(255, 255, 255));
        lblCPF.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblCPF.setForeground(new java.awt.Color(255, 255, 255));
        lblCPF.setText("CPF");
        contentPane.add(lblCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        lblNomeEmpresa.setBackground(new java.awt.Color(255, 255, 255));
        lblNomeEmpresa.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNomeEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        lblNomeEmpresa.setText("Nome/Empresa");
        contentPane.add(lblNomeEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));
        contentPane.add(txtMunicipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 250, -1));
        contentPane.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 60, -1));
        contentPane.add(txtEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 250, -1));

        txtNomeEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeEmpresaActionPerformed(evt);
            }
        });
        contentPane.add(txtNomeEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 250, -1));

        contentPane.add(cmbPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 280, -1));

        try {
            txtCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        contentPane.add(txtCEP, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 200, -1));

        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefoneActionPerformed(evt);
            }
        });
        contentPane.add(txtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 200, -1));

        try {
            txtCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        contentPane.add(txtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 200, -1));

        bttExcluir.setIcon(new javax.swing.ImageIcon("D:\\Hugo Christian\\Aplicativos\\Icones\\bttExcluir.png")); // NOI18N
        contentPane.add(bttExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, -1, -1));
        contentPane.add(txtCNPJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 200, -1));

        bttPesquisar.setIcon(new javax.swing.ImageIcon("D:\\Hugo Christian\\Aplicativos\\Icones\\bttPesquisar.png")); // NOI18N
        contentPane.add(bttPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, -1, -1));

        bttEditar.setIcon(new javax.swing.ImageIcon("D:\\Hugo Christian\\Aplicativos\\Icones\\bttEditar.png")); // NOI18N
        contentPane.add(bttEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, -1, -1));

        bttGravar.setIcon(new javax.swing.ImageIcon("D:\\Hugo Christian\\Aplicativos\\Icones\\bttGravar.png")); // NOI18N
        contentPane.add(bttGravar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, -1, -1));

        bttLimpar.setIcon(new javax.swing.ImageIcon("D:\\Hugo Christian\\Aplicativos\\Icones\\bttLimpar.png")); // NOI18N
        bttLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttLimparActionPerformed(evt);
            }
        });
        contentPane.add(bttLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, -1, -1));

        rbGeneroM.setBackground(new java.awt.Color(0, 51, 51));
        buttonGroup1.add(rbGeneroM);
        rbGeneroM.setForeground(new java.awt.Color(255, 255, 255));
        rbGeneroM.setText("M");
        rbGeneroM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbGeneroMActionPerformed(evt);
            }
        });
        contentPane.add(rbGeneroM, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, -1, -1));

        rbGeneroF.setBackground(new java.awt.Color(0, 51, 51));
        buttonGroup1.add(rbGeneroF);
        rbGeneroF.setForeground(new java.awt.Color(255, 255, 255));
        rbGeneroF.setText("F");
        rbGeneroF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbGeneroFActionPerformed(evt);
            }
        });
        contentPane.add(rbGeneroF, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, -1, -1));
        contentPane.add(txtCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 200, -1));

        getContentPane().add(contentPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeEmpresaActionPerformed

    private void txtTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefoneActionPerformed

    private void bttLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttLimparActionPerformed
        limparTela();
    }//GEN-LAST:event_bttLimparActionPerformed

    private void rbGeneroFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbGeneroFActionPerformed
        genero = "F";
    }//GEN-LAST:event_rbGeneroFActionPerformed

    private void rbGeneroMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbGeneroMActionPerformed
        genero = "M";
    }//GEN-LAST:event_rbGeneroMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttEditar;
    private javax.swing.JButton bttExcluir;
    private javax.swing.JButton bttGravar;
    private javax.swing.JButton bttLimpar;
    private javax.swing.JButton bttPesquisar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JComboBox<String> cmbPesquisar;
    private javax.swing.JPanel contentPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCEP;
    private javax.swing.JLabel lblCNPJ;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblMunicipio;
    private javax.swing.JLabel lblNomeEmpresa;
    private javax.swing.JLabel lblPesquisar;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JRadioButton rbGeneroF;
    private javax.swing.JRadioButton rbGeneroM;
    private javax.swing.JFormattedTextField txtCEP;
    private javax.swing.JFormattedTextField txtCNPJ;
    private javax.swing.JFormattedTextField txtCPF;
    private javax.swing.JFormattedTextField txtCelular;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtMunicipio;
    private javax.swing.JTextField txtNomeEmpresa;
    private javax.swing.JFormattedTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
